name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: devsecops-app

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: app/app
        run: npm install

      # ---------------- SNYK ----------------
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Security Scan
        run: |
          cd app/app
          snyk test --severity-threshold=high --debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---------------- DOCKER BUILD ----------------
      - name: Build Docker Image
        run: docker build -t $ECR_REPOSITORY:latest ./app/app

      # ---------------- TRIVY ----------------
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:latest

      # ---------------- AWS LOGIN ----------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------- PUSH TO ECR ----------------
      - name: Tag & Push Image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URI=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY

          docker tag $ECR_REPOSITORY:latest $ECR_URI:latest
          docker push $ECR_URI:latest

      # ---------------- UPDATE KUBECONFIG ----------------
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name devsecops-cluster --region $AWS_REGION

      # ---------------- DEPLOY ----------------
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
